name: auto add template comment to cuixiaorui/study-every-day issue
on:
  schedule:
    - cron "30 0 * * *"
jobs:
  add-comment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run:
          "npm install"
          "node dist/index.ts"
