name: auto add template comment to cuixiaorui/study-every-day issue

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 0 * * *'

jobs:
  add-comment:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CANCEL_SUB: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: tsc
      - run: node dist/index.js
