name: auto add template comment to cuixiaorui/study-every-day issue
on:
  schedule:
    - cron "30 0 * * *"
jobs:
  add-comment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        env:
          GH_TOKEN: ${{ secret.GH_TOKEN }}
    - run: npm install
    - run: npm test
